version: '3'

services:
  app:
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    environment:
      APP_ENV: "prod"
      APP_DEBUG: "False"
      MONGODB_DATABASE: fastapidb
      MONGODB_USERNAME: fastapiuser
      MONGODB_PASSWORD: your_mongodb_password
      MONGODB_HOSTNAME: mongodb
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.0.8
    container_name: mongodb
    restart: unless-stopped
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodbuser
      MONGO_INITDB_ROOT_PASSWORD: your_mongodb_root_password
      MONGO_INITDB_DATABASE: fastapidb
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db

volumes:
  mongodbdata:
